[package]
name = "quicos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "io-util"], default-features = false }
bytes = { version = "1.7", default-features = false }